name: 测试Issue模版名字
description: Issue模版描述
labels: bug
assignees: 
  - weihongbin1
title: Issue标题
body:
  - type: markdown
    attributes:
      value: |
        # 这里是 Markdown 表单
        <p align="center"><a href="https://nextjs.org"><picture><source media="(prefers-color-scheme: dark)"srcset="https://assets.vercel.com/image/upload/v1662130559/nextjs/Icon_dark_background.png"><img src="https://assets.vercel.com/image/upload/v1662130559/nextjs/Icon_light_background.png"height="128"></picture><h1 align="center">Next.js</h1></a></p>
  - type: checkboxes
    id: my-checkbox
    attributes:
      label: 多选框
      description: 多选框提示
      options:
        - label: 选择内容1
          required: true
        - label: 选择内容2 非必选
          required: false
  - type: textarea
    id: my-textarea
    attributes:
      label: 文本框
      description: 文本框提示
      render: Shell
      placeholder: 文本框内部提示
    validations:
      required: true
  - type: textarea
    id: my-textarea2
    attributes:
      label: 文本框2
      description: 文本框提示2
      render: Markdown
      value: 文本框 Value
    validations:
      required: false
  - type: textarea
    id: my-textarea3
    attributes:
      label: 文本框3
      description: 文本框提示3
    validations:
      required: false
  - type: input
    id: my-input
    attributes:
      label: 输入框
      description: 输入框提示
      placeholder: 输入框内部提示
      value: 输入框 Value
    validations:
      required: true
  - type: dropdown
    id: my-dropdown
    attributes:
      label: 下拉框
      description: 下拉框提示
      options:
        - 选择内容1
        - 选择内容2
        - 选择内容3
    validations:
      required: true
  - type: dropdown
    id: my-dropdown2
    attributes:
      label: 下拉框2
      multiple: true
      description: 下拉框提示2
      options:
        - 选择内容1
        - 选择内容2
        - 选择内容3
    validations:
      required: false
